---
title: "{{ cookiecutter.project }}"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r, include=FALSE}
datadir <- "../data"
library(tidyverse)
source("../src/utils.R")
```
{{ cookiecutter.project_short_description }}

# Overview

Analysis notebooks are the central component of an analysis project and are the main deliverable for a project. Delete these instructions and replace with your own documentation, code, figures, and tables.

## Project guidelines
- Use this notebook (`./notebook.Rmd`) as your landing page, and delete any other notebook stubs, such as `notebook.ipynb`. Supplementary material (such as external websites, additional notebooks, or figures) are allowed but must have a link from this page.
- Keep the analysis self-contained by adding dependencies to the Dockerfile.
- Save raw data in `./data` and processed data or figures in `./results`. Use [git lfs](https://git-lfs.github.com/) to track large files instead of adding to the git repo
- Use calls to data APIs instead of batch downloads when possible
